package com.ordo.itsm.audit;

public enum AuditAction {
    TICKET_CREATED,
    AI_TRIAGED,
    AI_TRIAGE_FAILED,
    TRIAGE_CONFIRMED,
    TICKET_UPDATED,
    INFO_SUPPLEMENTED,
    RISK_ASSESSED,
    RISK_REASSESSED,
    TICKET_ASSIGNED,
    STATUS_CHANGED,
    SLA_PAUSED,
    SLA_RESUMED,
    APPROVAL_REQUESTED,
    APPROVED,
    REJECTED,
    COMMENT_ADDED,
    LOGIN_FAILED,
    ACCESS_DENIED
}
